import {useEffect,useState} from 'react'
import {api} from '../api'
import '../styles/workspace-pages.css'

type Message={id:number;content:string;senderType:string;agentName:string|null;createdAt:string}
type Conversation={id:number;subject:string;visitorName:string|null;visitorEmail:string|null;status:string;createdAt:string;updatedAt:string;messages:Message[]}

export default function InboxPage(){
  const [items,setItems]=useState<Conversation[]>([]),[selected,setSelected]=useState<Conversation>(),[reply,setReply]=useState(''),[error,setError]=useState(''),[menu,setMenu]=useState(false)
  useEffect(()=>{void api<Conversation[]>('/api/support/inbox').then(setItems).catch(e=>setError(e instanceof Error?e.message:'Impossible de charger la boîte de réception.'))},[])
  useEffect(()=>{const source=new EventSource('/api/realtime/inbox',{withCredentials:true});source.addEventListener('conversation',event=>{const next=JSON.parse((event as MessageEvent).data) as Conversation;setItems(current=>current.some(item=>item.id===next.id)?current.map(item=>item.id===next.id?next:item):[next,...current]);setSelected(current=>current?.id===next.id?next:current);document.title='● Nouveau message · Support'});return()=>source.close()},[])
  async function sendReply(){if(!selected||!reply.trim())return;try{const updated=await api<Conversation>(`/api/support/conversations/${selected.id}/replies`,{method:'POST',body:JSON.stringify({content:reply})});setItems(v=>v.map(item=>item.id===updated.id?updated:item));setSelected(updated);setReply('')}catch(e){setError(e instanceof Error?e.message:'Impossible d’envoyer la réponse.')}}
  async function deleteConversation(){if(!selected||!window.confirm('Supprimer toute cette conversation et tous ses messages ?'))return;try{await api<void>(`/api/support/conversations/${selected.id}`,{method:'DELETE'});setItems(v=>v.filter(item=>item.id!==selected.id));setSelected(undefined);setMenu(false)}catch(e){setError(e instanceof Error?e.message:'Impossible de supprimer la conversation.')}}
  return <div className="page"><div className="page-head"><div><span className="eyebrow">SUPPORT</span><h1 className="title">Boîte de réception</h1><p>Ouvrez une conversation pour répondre au client.</p></div></div>{error&&<div className="form-error" role="alert">{error}</div>}<div className="split-layout"><section className="content-card"><div className="card-head"><div><h2>Conversations</h2><p>{items.length} message{items.length>1?'s':''}</p></div></div>{items.length===0?<div className="empty"><b>Aucune conversation.</b><span>Les demandes support apparaîtront ici.</span></div>:<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Sujet</th><th>Client</th><th>Date</th><th>Statut</th></tr></thead><tbody>{items.map(item=><tr key={item.id} className={selected?.id===item.id?'selected-row':''} onClick={()=>{setSelected(item);setMenu(false)}}><td><button className="campaign-row"><span className="survey-avatar">{(item.subject || 'S').slice(0,1).toUpperCase()}</span><span className="campaign-info"><b>{item.subject}</b><small>{item.messages[item.messages.length-1]?.content||'Aucun message'}</small></span></button></td><td>{item.visitorName||item.visitorEmail||'Visiteur'}</td><td>{new Date(item.updatedAt).toLocaleString('fr-FR')}</td><td><span className={`status-badge ${item.status.toLowerCase().replace(/\s+/g,'-')}`}>{item.status}</span></td></tr>)}</tbody></table></div>}</section>{selected&&<section className="content-card support-detail"><div className="card-head"><div><h2>{selected.subject}</h2><p>{selected.visitorName||'Visiteur'}{selected.visitorEmail&&` · ${selected.visitorEmail}`}</p></div><div className="conversation-menu"><button className="icon-btn" onClick={()=>setMenu(!menu)} aria-label="Options de la conversation">•••</button>{menu&&<button className="delete-message" onClick={()=>void deleteConversation()}>Supprimer la conversation</button>}</div></div><div className="intercom-messages">{selected.messages.map(message=><div className={message.senderType==='AGENT'?'support-message user':'support-message ai'} key={message.id}><p><b>{message.senderType==='AGENT'?(message.agentName||'Agent'):'Client'}</b><br/>{message.content}<small>{new Date(message.createdAt).toLocaleString('fr-FR')}</small></p></div>)}</div><div className="intercom-compose"><input value={reply} onChange={e=>setReply(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void sendReply()}} placeholder="Répondre au client…"/><button onClick={()=>void sendReply()}>Répondre</button></div></section>}</div></div>
}
