import {useEffect,useRef,useState} from 'react'
import {createPortal} from 'react-dom'
import {api} from '../api'
import './intercom-widget.css'

type Message={from:'ai'|'user';text:string}
type SupportMessage={id:number;content:string;senderType:string;agentName:string|null;createdAt:string}
type Conversation={id:number;messages:SupportMessage[]}

async function findVisitorConversation():Promise<Conversation|undefined>{
  const response=await fetch(`/api/support/conversations?visitorKey=${encodeURIComponent(getVisitorId())}`,{credentials:'include',cache:'no-store'})
  if(!response.ok)return undefined
  return response.json() as Promise<Conversation>
}

export function IntercomWidget({compact=false}:{compact?:boolean}){
  const [open,setOpen]=useState(false),[tab,setTab]=useState<'assistant'|'support'>('assistant'),[text,setText]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false)
  const [messages,setMessages]=useState<Message[]>([{from:'ai',text:'Bonjour ! Je peux vous aider avec les enquêtes, les réponses ou les analytics.'}]),[conversation,setConversation]=useState<Conversation>(),lastMessage=useRef(0)
  const [position,setPosition]=useState<{x:number;y:number}|null>(()=>{try{const saved=localStorage.getItem('afriland-support-position');return saved?JSON.parse(saved):null}catch{return null}})
  const dragging=useRef(false), moved=useRef(false), offset=useRef({x:0,y:0}),startPoint=useRef({x:0,y:0}),launcherRef=useRef<HTMLButtonElement>(null)
  useEffect(()=>{if(position)localStorage.setItem('afriland-support-position',JSON.stringify(position))},[position])
  function startDrag(event:React.PointerEvent<HTMLButtonElement>){if(event.button!==0)return;const rect=event.currentTarget.getBoundingClientRect();dragging.current=true;moved.current=false;startPoint.current={x:event.clientX,y:event.clientY};offset.current={x:event.clientX-rect.left,y:event.clientY-rect.top};event.currentTarget.setPointerCapture(event.pointerId)}
  function drag(clientX:number,clientY:number){if(!dragging.current||!launcherRef.current)return;const distance=Math.hypot(clientX-startPoint.current.x,clientY-startPoint.current.y);if(distance<8)return;moved.current=true;const size=launcherRef.current.getBoundingClientRect();const x=Math.max(0,Math.min(window.innerWidth-size.width,clientX-offset.current.x));const y=Math.max(0,Math.min(window.innerHeight-size.height,clientY-offset.current.y));setPosition({x,y})}
  function stopDrag(){if(!dragging.current)return;dragging.current=false}
  useEffect(()=>{const move=(event:PointerEvent)=>drag(event.clientX,event.clientY);const stop=()=>stopDrag();window.addEventListener('pointermove',move);window.addEventListener('pointerup',stop);window.addEventListener('pointercancel',stop);return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',stop);window.removeEventListener('pointercancel',stop)}},[])
  useEffect(()=>{if(!open||tab!=='support'||conversation)return;void findVisitorConversation().then(result=>{if(!result)return;setConversation(result);setSent(true);lastMessage.current=result.messages[result.messages.length-1]?.id||0}).catch(()=>{})},[open,tab,conversation])
  useEffect(()=>{if(!conversation?.id)return;const refreshConversation=()=>{void findVisitorConversation().then(next=>{if(!next)return;const newest=next.messages[next.messages.length-1];if(newest&&newest.id>lastMessage.current&&newest.senderType!=='USER'){if(lastMessage.current)playNotification();lastMessage.current=newest.id;setConversation(next)}})};const onVisibility=()=>{if(document.visibilityState==='visible')refreshConversation()};window.addEventListener('online',refreshConversation);document.addEventListener('visibilitychange',onVisibility);return()=>{window.removeEventListener('online',refreshConversation);document.removeEventListener('visibilitychange',onVisibility)}},[conversation?.id])
  function ask(){const message=text.trim();if(!message||busy)return;  setBusy(true);setMessages(v=>[...v,{from:'user',text:message}]);setText('');void api<{answer:string}>('/api/support/ai',{method:'POST',body:JSON.stringify({prompt:message})}).then(r=>setMessages(v=>[...v,{from:'ai',text:r.answer}])).catch(e=>setMessages(v=>[...v,{from:'ai',text:e instanceof Error?e.message:"L’assistant est momentanément indisponible."}])).finally(()=>setBusy(false))}
  function sendSupport(){const message=text.trim();if(!message||busy)return;setBusy(true);void api<Conversation>('/api/support/conversations',{method:'POST',body:JSON.stringify({visitorKey:getVisitorId(),subject:'Demande depuis le site',message})}).then(result=>{setConversation(result);lastMessage.current=result.messages[result.messages.length-1]?.id||0;setText('');setSent(true)}).catch(e=>setMessages(v=>[...v,{from:'ai',text:e instanceof Error?e.message:"Impossible d’envoyer la demande."}])).finally(()=>setBusy(false))}
  function sendVisitorMessage(){const message=text.trim();if(!conversation||!message||busy)return;setBusy(true);void api<Conversation>(`/api/support/conversations/${conversation.id}/messages`,{method:'POST',body:JSON.stringify({visitorKey:getVisitorId(),content:message})}).then(result=>{setConversation(result);lastMessage.current=result.messages[result.messages.length-1]?.id||lastMessage.current;setText('')}).catch(e=>setMessages(v=>[...v,{from:'ai',text:e instanceof Error?e.message:"Impossible d’envoyer le message."}])).finally(()=>setBusy(false))}
  return createPortal(<div className={compact?"intercom-widget compact":"intercom-widget"} style={position?{position:'fixed',left:position.x,top:position.y,right:'auto',bottom:'auto'}:undefined}>{open&&<section className="intercom-panel" aria-label="Centre d'aide"><header><div><strong>Bonjour 👋</strong><span>Assistance Afriland</span></div><button onClick={()=>setOpen(false)} aria-label="Fermer">×</button></header><div className="intercom-tabs"><button className={tab==='assistant'?'active':''} onClick={()=>setTab('assistant')}>Assistant IA</button><button className={tab==='support'?'active':''} onClick={()=>{setTab('support');setSent(false)}}>Contacter l’équipe</button></div>  {tab==='assistant'?<div className="intercom-body"><div className="intercom-messages">{messages.map((m,i)=><p key={i} className={m.from}>{m.text}</p>)}</div><div className="intercom-compose"><input disabled={busy} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')ask()}} placeholder="Posez votre question…"/><button disabled={busy} onClick={ask}>{busy?'…':'Envoyer'}</button></div></div>:<div className="intercom-body">{sent&&conversation?<><div className="intercom-messages">{conversation.messages.map(message=><p key={message.id} className={message.senderType==='AGENT'?'ai':'user'}>{message.content}<small>{new Date(message.createdAt).toLocaleString('fr-FR')}</small></p>)}</div><div className="intercom-compose"><input disabled={busy} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void sendVisitorMessage()}} placeholder="Écrire à l’équipe…"/><button disabled={busy} onClick={()=>void sendVisitorMessage()}>Envoyer</button></div></>:<><p className="intercom-intro">Décrivez votre demande, notre équipe vous répondra.</p><div className="intercom-compose vertical"><textarea disabled={busy} value={text} onChange={e=>setText(e.target.value)} placeholder="Votre demande…"/><button disabled={busy} onClick={sendSupport}>{busy?'Envoi…':'Envoyer au support'}</button></div></>}</div>}<footer>Propulsé par Afriland First Bank</footer></section>}<button ref={launcherRef} className={open?'intercom-launcher open':'intercom-launcher'} onPointerDown={startDrag} onPointerUp={stopDrag} onPointerCancel={stopDrag} onClick={()=>{if(moved.current){window.setTimeout(()=>{moved.current=false},0);return}setOpen(v=>!v)}} aria-label={open?'Fermer le centre d’aide':'Ouvrir le centre d’aide'} title="Déplacer l’assistance ou cliquer pour ouvrir">  <span className="intercom-dot"/><span className="intercom-bubble">▰</span></button></div>,document.body)
}
function getVisitorId(){const key='afriland-support-visitor',existing=localStorage.getItem(key);if(existing)return existing;const id=crypto.randomUUID();localStorage.setItem(key,id);return id}
function playNotification(){const context=new AudioContext(),oscillator=context.createOscillator(),gain=context.createGain();oscillator.frequency.value=740;gain.gain.value=.08;oscillator.connect(gain);gain.connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+.12)}
