import { NavLink, Outlet, useNavigate } from 'react-router-dom'
import { Icon } from './Icons'
import { useAuth } from '../context/AuthContext'
import { useTheme } from '../context/ThemeContext'
import './workspace.css'
import { IntercomWidget } from './IntercomWidget'

const items=[['/bureau','Dashboard','grid'],['/bureau/enquetes','Enquêtes','survey'],['/bureau/reponses','Réponses','reply'],['/bureau/inbox','Support','reply'],['/bureau/analytics','Analytics','chart'],['/bureau/parametres','Paramètres','settings']] as const
export function WorkspaceLayout(){const {user,logout}=useAuth();const {theme,toggle}=useTheme();const nav=useNavigate();if(!user)return null;const initials=user.identifiant.slice(0,1).toUpperCase();return <div className="workspace"><aside className="sidebar"><div className="brand-lockup"><img className="brand-logo" src="/logo-afriland.png" alt="Afriland First Bank"/></div><div className="side-label">ESPACE ENQUÊTES</div><nav>{items.map(([to,label,icon])=><NavLink key={to} to={to} className={({isActive})=>isActive?'nav-item active':'nav-item'} end={to==='/bureau'}><Icon name={icon}/><span>{label}</span></NavLink>)}</nav><button className="side-create" onClick={()=>nav('/bureau/enquetes/nouvelle')}><Icon name="plus"/>Créer une enquête</button><div className="sidebar-spacer"/><button className="nav-item logout" onClick={async()=>{await logout();nav('/identification')}}><Icon name="logout"/><span>Se déconnecter</span></button></aside><section className="workspace-main"><header className="topbar"><div className="topbar-search"><Icon name="search"/><input placeholder="Rechercher une enquête..." /></div><div className="topbar-actions"><button className="icon-btn" onClick={toggle} title="Changer le thème"><Icon name={theme==='dark'?'sun':'moon'}/></button><button className="profile-pill" onClick={()=>nav('/bureau/profil')}><div className="avatar">{user.photoUrl?<img src={user.photoUrl} alt=""/>:initials}</div><div><strong>{user.identifiant}</strong><span>{user.email||'Compte personnel'}</span></div></button></div></header><main className="workspace-content"><Outlet/></main></section><IntercomWidget/></div>}
